esphome:
  name: louder-esp32
  friendly_name: louder-esp32
  platformio_options:
    board_build.arduino.memory_type: qio_opi
  on_boot:
  ## use priority 250 so gpio and i2c dac is setup before volume is set
    priority: 250
    then:
    ## Set a volume limit just to be safe...
    - media_player.volume_set:
        id: louder_mediaplayer
        volume: 10%

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: arduino

# Enable logging
logger:


# Enable Home Assistant API
api:
  encryption:
    key: !secret louder_api

ota:
  - platform: esphome
    password: !secret louder_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

psram:
  mode: octal
  speed: 80MHz

external_components:
  - source: github://mrtoy-me/esphome-components-test@main
    components: [ tas5805m ]
    refresh: 0s

i2c:
  sda: GPIO8
  scl: GPIO9
  frequency: 400kHz
  timeout: 10ms
  scan: True

audio_dac:
  - platform: tas5805m
    id: tas5805_dac
    enable_pin: GPIO17

i2s_audio:
  i2s_lrclk_pin: GPIO15
  i2s_bclk_pin: GPIO14

media_player:
  - platform: i2s_audio
    name: Louder-ESP32 mediaplayer
    id: louder_mediaplayer
    dac_type: external
    i2s_dout_pin: GPIO16
    mode: stereo
    on_play:
      - switch.turn_on: enable_louder

switch:
  - platform: template
    name: Enable Louder-ESP32
    id: enable_louder
    optimistic: true
    turn_on_action:
      - lambda: !lambda |-
          id(tas5805_dac).set_deep_sleep_off();
    turn_off_action:
      - lambda: !lambda |-
          id(tas5805_dac).set_deep_sleep_on();

interval:
  - interval: 1min
    then:
      - if:
          condition:
            - switch.is_on: enable_louder
            - for:
                time: 30s
                condition:
                  or:
                    - media_player.is_idle: louder_mediaplayer
                    - media_player.is_paused: louder_mediaplayer
          then:
            - switch.turn_off: enable_louder
